name: ${project.name}
version: ${project.version}
api: ["1.0.8"]
author: MEFRREEX
main: com.mefrreex.infotool.InfoTool

permissions:
  infotool.use:
    default: op
  infotool.about:
    default: true
