name: ${project.name}
version: ${project.version}
api: ["1.0.8"]
author: The Oni
description: ${project.description}
main: theoni.infotool.Main

permissions:
  infotool.use:
    default: op
  infotool.about:
    default: true
